export const MOCK_LISTINGS = [
  // ── Australian properties ───────────────────────────────────────────────
  {
    id: 'au-001',
    referenceNo: 'AU-001',
    propertyAddress: '42 Prospect Street',
    suburb: 'Prospect SA 5082, Australia',
    country: 'AU',
    countryLabel: 'Australia',
    purchasePrice: 750000,
    currency: 'AUD',
    statusLabel: 'Active',
    statusColor: 'bg-blue-100 text-blue-700',
    settlementDate: '10 Jun 2026',
    daysToSettle: 20,
    conditionsMet: 3,
    conditionsTotal: 4,
    titleRef: 'CT 5432/876',
    deposit: '$75,000 AUD',
    depositPaid: true,
    parties: ['J', 'E', 'S', 'D'],
    settled: false,
    type: '4BR House',
    notes: 'Finance and inspections cleared. Awaiting Section 7 certificate.',
    flag: '🇦🇺',
    imageUrl: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'au-002',
    referenceNo: 'AU-002',
    propertyAddress: '15 King William Road',
    suburb: 'Unley SA 5061, Australia',
    country: 'AU',
    countryLabel: 'Australia',
    purchasePrice: 1200000,
    currency: 'AUD',
    statusLabel: 'Active',
    statusColor: 'bg-blue-100 text-blue-700',
    settlementDate: '18 Jul 2026',
    daysToSettle: 58,
    conditionsMet: 0,
    conditionsTotal: 3,
    titleRef: 'CT 6701/234',
    deposit: '$120,000 AUD',
    depositPaid: false,
    parties: ['S', 'D'],
    settled: false,
    type: '5BR Heritage Home',
    notes: 'High-value property. Finance condition expires 30 May.',
    flag: '🇦🇺',
    imageUrl: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'au-003',
    referenceNo: 'AU-003',
    propertyAddress: '8 Greenhill Road',
    suburb: 'Tusmore SA 5065, Australia',
    country: 'AU',
    countryLabel: 'Australia',
    purchasePrice: 980000,
    currency: 'AUD',
    statusLabel: 'Settled',
    statusColor: 'bg-green-100 text-green-700',
    settlementDate: '25 Apr 2026',
    daysToSettle: -1,
    conditionsMet: 0,
    conditionsTotal: 0,
    titleRef: 'CT 4219/551',
    deposit: '$98,000 AUD',
    depositPaid: true,
    parties: ['S', 'D'],
    settled: true,
    type: '4BR Executive',
    notes: 'Settlement completed via PEXA on 25 Apr 2026.',
    flag: '🇦🇺',
    imageUrl: 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'au-004',
    referenceNo: 'AU-004',
    propertyAddress: '3 Moseley Square',
    suburb: 'Glenelg SA 5045, Australia',
    country: 'AU',
    countryLabel: 'Australia',
    purchasePrice: 1450000,
    currency: 'AUD',
    statusLabel: 'Active',
    statusColor: 'bg-blue-100 text-blue-700',
    settlementDate: '5 Aug 2026',
    daysToSettle: 76,
    conditionsMet: 1,
    conditionsTotal: 3,
    titleRef: 'CT 7823/109',
    deposit: '$145,000 AUD',
    depositPaid: true,
    parties: ['M', 'P', 'D'],
    settled: false,
    type: '4BR Beachside',
    notes: 'Coastal property 150m from beach. Strata plan lodged. PEXA workspace open.',
    flag: '🇦🇺',
    imageUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'au-005',
    referenceNo: 'AU-005',
    propertyAddress: '22 O\'Connell Street',
    suburb: 'North Adelaide SA 5006, Australia',
    country: 'AU',
    countryLabel: 'Australia',
    purchasePrice: 620000,
    currency: 'AUD',
    statusLabel: 'Ready',
    statusColor: 'bg-amber-100 text-amber-700',
    settlementDate: '28 May 2026',
    daysToSettle: 7,
    conditionsMet: 4,
    conditionsTotal: 4,
    titleRef: 'CT 3310/782',
    deposit: '$62,000 AUD',
    depositPaid: true,
    parties: ['L', 'R'],
    settled: false,
    type: '2BR Apartment',
    notes: 'All conditions met. PEXA settlement booked for 28 May.',
    flag: '🇦🇺',
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'au-006',
    referenceNo: 'AU-006',
    propertyAddress: '55 Norwood Parade',
    suburb: 'Norwood SA 5067, Australia',
    country: 'AU',
    countryLabel: 'Australia',
    purchasePrice: 890000,
    currency: 'AUD',
    statusLabel: 'Settled',
    statusColor: 'bg-green-100 text-green-700',
    settlementDate: '12 Mar 2026',
    daysToSettle: -1,
    conditionsMet: 0,
    conditionsTotal: 0,
    titleRef: 'CT 5091/340',
    deposit: '$89,000 AUD',
    depositPaid: true,
    parties: ['T', 'A'],
    settled: true,
    type: '3BR Terrace',
    notes: 'Heritage-listed terrace. Settlement completed via PEXA.',
    flag: '🇦🇺',
    imageUrl: 'https://images.unsplash.com/photo-1605146769289-4be4bbfb3c76?auto=format&fit=crop&w=600&q=80',
  },

  // ── Bali properties ─────────────────────────────────────────────────────
  {
    id: 'bali-001',
    referenceNo: 'BALI-001',
    propertyAddress: 'Villa Karang Sunset',
    suburb: 'Seminyak, Bali, Indonesia',
    country: 'ID',
    countryLabel: 'Bali, Indonesia',
    purchasePrice: 485000,
    currency: 'AUD',
    statusLabel: 'Active',
    statusColor: 'bg-blue-100 text-blue-700',
    settlementDate: '15 Jun 2026',
    daysToSettle: 25,
    conditionsMet: 2,
    conditionsTotal: 4,
    titleRef: 'HGB-SMY-2241',
    deposit: '$48,500 AUD',
    depositPaid: true,
    parties: ['A', 'B', 'N'],
    settled: false,
    type: '3BR Private Villa',
    notes: 'Leasehold 25yr + 25yr. Notarial deed lodged with PPAT. Pool & tropical garden.',
    flag: '🇮🇩',
    imageUrl: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'bali-002',
    referenceNo: 'BALI-002',
    propertyAddress: 'The Layar Private Estate',
    suburb: 'Canggu, Bali, Indonesia',
    country: 'ID',
    countryLabel: 'Bali, Indonesia',
    purchasePrice: 1850000,
    currency: 'AUD',
    statusLabel: 'Active',
    statusColor: 'bg-blue-100 text-blue-700',
    settlementDate: '30 Jul 2026',
    daysToSettle: 70,
    conditionsMet: 1,
    conditionsTotal: 5,
    titleRef: 'HGB-CGU-0887',
    deposit: '$185,000 AUD',
    depositPaid: true,
    parties: ['M', 'R', 'N', 'P'],
    settled: false,
    type: '5BR Luxury Estate',
    notes: 'Freehold Hak Milik via Indonesian nominee. Infinity pool, 2,400m² land.',
    flag: '🇮🇩',
    imageUrl: 'https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'bali-003',
    referenceNo: 'BALI-003',
    propertyAddress: 'Cliff Edge Villa Uluwatu',
    suburb: 'Uluwatu, Bali, Indonesia',
    country: 'ID',
    countryLabel: 'Bali, Indonesia',
    purchasePrice: 620000,
    currency: 'AUD',
    statusLabel: 'Settled',
    statusColor: 'bg-green-100 text-green-700',
    settlementDate: '10 Mar 2026',
    daysToSettle: -1,
    conditionsMet: 0,
    conditionsTotal: 0,
    titleRef: 'HGB-ULW-1193',
    deposit: '$62,000 AUD',
    depositPaid: true,
    parties: ['T', 'N'],
    settled: true,
    type: '3BR Ocean-View Villa',
    notes: 'Leasehold 30yr. Title transferred and registered. Direct ocean view.',
    flag: '🇮🇩',
    imageUrl: 'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'bali-004',
    referenceNo: 'BALI-004',
    propertyAddress: 'Jungle Retreat Ubud',
    suburb: 'Ubud, Bali, Indonesia',
    country: 'ID',
    countryLabel: 'Bali, Indonesia',
    purchasePrice: 395000,
    currency: 'AUD',
    statusLabel: 'Active',
    statusColor: 'bg-blue-100 text-blue-700',
    settlementDate: '22 Jun 2026',
    daysToSettle: 32,
    conditionsMet: 2,
    conditionsTotal: 3,
    titleRef: 'HGB-UBD-3312',
    deposit: '$39,500 AUD',
    depositPaid: true,
    parties: ['C', 'W', 'N'],
    settled: false,
    type: '2BR Jungle Villa',
    notes: 'Leasehold 30yr. Rice terrace views. Surrounded by tropical forest.',
    flag: '🇮🇩',
    imageUrl: 'https://images.unsplash.com/photo-1555400038-63f5ba517a47?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'bali-005',
    referenceNo: 'BALI-005',
    propertyAddress: 'Nusa Dua Beachfront Villa',
    suburb: 'Nusa Dua, Bali, Indonesia',
    country: 'ID',
    countryLabel: 'Bali, Indonesia',
    purchasePrice: 2200000,
    currency: 'AUD',
    statusLabel: 'Active',
    statusColor: 'bg-blue-100 text-blue-700',
    settlementDate: '15 Sep 2026',
    daysToSettle: 117,
    conditionsMet: 0,
    conditionsTotal: 4,
    titleRef: 'HGB-NSD-0551',
    deposit: '$220,000 AUD',
    depositPaid: false,
    parties: ['H', 'K', 'N'],
    settled: false,
    type: '6BR Beachfront Estate',
    notes: 'Direct beachfront. Hak Milik title. 4,000m² land with private beach access.',
    flag: '🇮🇩',
    imageUrl: 'https://images.unsplash.com/photo-1615460549969-36fa19521a4f?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'bali-006',
    referenceNo: 'BALI-006',
    propertyAddress: 'Sanur Sunrise Residence',
    suburb: 'Sanur, Bali, Indonesia',
    country: 'ID',
    countryLabel: 'Bali, Indonesia',
    purchasePrice: 520000,
    currency: 'AUD',
    statusLabel: 'Settled',
    statusColor: 'bg-green-100 text-green-700',
    settlementDate: '5 Feb 2026',
    daysToSettle: -1,
    conditionsMet: 0,
    conditionsTotal: 0,
    titleRef: 'HGB-SNR-2078',
    deposit: '$52,000 AUD',
    depositPaid: true,
    parties: ['F', 'G'],
    settled: true,
    type: '3BR Garden Villa',
    notes: 'Leasehold 25yr. 800m to beach. Settlement completed.',
    flag: '🇮🇩',
    imageUrl: 'https://images.unsplash.com/photo-1562790351-d273a961e0e9?auto=format&fit=crop&w=600&q=80',
  },
];
