export const MOCK_LISTINGS = [
  // ── Australian properties ───────────────────────────────────────────────
  {
    id: 'au-001',
    referenceNo: 'AU-001',
    propertyAddress: '42 Prospect Street',
    suburb: 'Prospect SA 5082, Australia',
    country: 'AU',
    countryLabel: 'Australia',
    purchasePrice: 750000,
    currency: 'AUD',
    statusLabel: 'Active',
    statusColor: 'bg-blue-100 text-blue-700',
    settlementDate: '10 Jun 2026',
    daysToSettle: 20,
    conditionsMet: 3,
    conditionsTotal: 4,
    titleRef: 'CT 5432/876',
    deposit: '$75,000 AUD',
    depositPaid: true,
    parties: ['J', 'E', 'S', 'D'],
    settled: false,
    type: '4BR House',
    notes: 'Finance and inspections cleared. Awaiting Section 7 certificate.',
    flag: '🇦🇺',
  },
  {
    id: 'au-002',
    referenceNo: 'AU-002',
    propertyAddress: '15 King William Road',
    suburb: 'Unley SA 5061, Australia',
    country: 'AU',
    countryLabel: 'Australia',
    purchasePrice: 1200000,
    currency: 'AUD',
    statusLabel: 'Active',
    statusColor: 'bg-blue-100 text-blue-700',
    settlementDate: '18 Jul 2026',
    daysToSettle: 58,
    conditionsMet: 0,
    conditionsTotal: 3,
    titleRef: 'CT 6701/234',
    deposit: '$120,000 AUD',
    depositPaid: false,
    parties: ['S', 'D'],
    settled: false,
    type: '5BR Heritage Home',
    notes: 'High-value property. Finance condition expires 30 May.',
    flag: '🇦🇺',
  },
  {
    id: 'au-003',
    referenceNo: 'AU-003',
    propertyAddress: '8 Greenhill Road',
    suburb: 'Tusmore SA 5065, Australia',
    country: 'AU',
    countryLabel: 'Australia',
    purchasePrice: 980000,
    currency: 'AUD',
    statusLabel: 'Settled',
    statusColor: 'bg-green-100 text-green-700',
    settlementDate: '25 Apr 2026',
    daysToSettle: -1,
    conditionsMet: 0,
    conditionsTotal: 0,
    titleRef: 'CT 4219/551',
    deposit: '$98,000 AUD',
    depositPaid: true,
    parties: ['S', 'D'],
    settled: true,
    type: '4BR Executive',
    notes: 'Settlement completed via PEXA on 25 Apr 2026.',
    flag: '🇦🇺',
  },

  // ── Bali properties ─────────────────────────────────────────────────────
  {
    id: 'bali-001',
    referenceNo: 'BALI-001',
    propertyAddress: 'Villa Karang Sunset',
    suburb: 'Seminyak, Bali, Indonesia',
    country: 'ID',
    countryLabel: 'Bali, Indonesia',
    purchasePrice: 485000,
    currency: 'AUD',
    statusLabel: 'Active',
    statusColor: 'bg-blue-100 text-blue-700',
    settlementDate: '15 Jun 2026',
    daysToSettle: 25,
    conditionsMet: 2,
    conditionsTotal: 4,
    titleRef: 'HGB-SMY-2241',
    deposit: '$48,500 AUD',
    depositPaid: true,
    parties: ['A', 'B', 'N'],
    settled: false,
    type: '3BR Private Villa',
    notes: 'Leasehold 25yr + 25yr. Notarial deed lodged with PPAT. Pool & tropical garden.',
    flag: '🇮🇩',
  },
  {
    id: 'bali-002',
    referenceNo: 'BALI-002',
    propertyAddress: 'The Layar Private Estate',
    suburb: 'Canggu, Bali, Indonesia',
    country: 'ID',
    countryLabel: 'Bali, Indonesia',
    purchasePrice: 1850000,
    currency: 'AUD',
    statusLabel: 'Active',
    statusColor: 'bg-blue-100 text-blue-700',
    settlementDate: '30 Jul 2026',
    daysToSettle: 70,
    conditionsMet: 1,
    conditionsTotal: 5,
    titleRef: 'HGB-CGU-0887',
    deposit: '$185,000 AUD',
    depositPaid: true,
    parties: ['M', 'R', 'N', 'P'],
    settled: false,
    type: '5BR Luxury Estate',
    notes: 'Freehold Hak Milik via Indonesian nominee. Infinity pool, 2,400m² land.',
    flag: '🇮🇩',
  },
  {
    id: 'bali-003',
    referenceNo: 'BALI-003',
    propertyAddress: 'Cliff Edge Villa Uluwatu',
    suburb: 'Uluwatu, Bali, Indonesia',
    country: 'ID',
    countryLabel: 'Bali, Indonesia',
    purchasePrice: 620000,
    currency: 'AUD',
    statusLabel: 'Settled',
    statusColor: 'bg-green-100 text-green-700',
    settlementDate: '10 Mar 2026',
    daysToSettle: -1,
    conditionsMet: 0,
    conditionsTotal: 0,
    titleRef: 'HGB-ULW-1193',
    deposit: '$62,000 AUD',
    depositPaid: true,
    parties: ['T', 'N'],
    settled: true,
    type: '3BR Ocean-View Villa',
    notes: 'Leasehold 30yr. Title transferred and registered. Direct ocean view.',
    flag: '🇮🇩',
  },
];
