// poolId links each listing to its specific InvestPool in investData.ts (null = no pool)
export const MOCK_LISTINGS = [
  // ── Australian properties ───────────────────────────────────────────────
  {
    id: 'au-001',
    poolId: 'p5',
    referenceNo: 'AU-001',
    propertyAddress: '42 Prospect Street',
    suburb: 'Prospect SA 5082, Australia',
    country: 'AU',
    countryLabel: 'Australia',
    purchasePrice: 750000,
    currency: 'AUD',
    statusLabel: 'Active',
    statusColor: 'bg-blue-100 text-blue-700',
    settlementDate: '10 Jun 2026',
    daysToSettle: 20,
    conditionsMet: 3,
    conditionsTotal: 4,
    titleRef: 'CT 5432/876',
    deposit: '$75,000 AUD',
    depositPaid: true,
    parties: ['J', 'E', 'S', 'D'],
    settled: false,
    type: '4BR House',
    beds: 4, baths: 2, parking: 2, landSize: '620 m²',
    description: 'A beautifully presented family home nestled in the heart of Prospect, one of Adelaide\'s most sought-after inner northern suburbs. This spacious 4-bedroom, 2-bathroom residence offers a perfect blend of classic character and modern living across a generous 620m² allotment.\n\nThe open-plan kitchen and living area flows seamlessly to an alfresco entertaining zone, ideal for year-round dining. The main bedroom features a walk-in robe and ensuite, while three additional bedrooms are serviced by a renovated family bathroom. A double garage with internal access completes the picture.',
    features: ['Open-plan kitchen & living', 'Alfresco entertaining', 'Main bedroom with ensuite & WIR', 'Ducted reverse-cycle A/C', 'Double lock-up garage', 'Fully landscaped garden', '620m² allotment', 'Walking distance to The Parade'],
    notes: 'Finance and inspections cleared. Awaiting Section 7 certificate.',
    flag: '🇦🇺',
    images: [
      'https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?auto=format&fit=crop&w=1200&q=80',
    ],
    agent: { name: 'Jane Cooper', role: "Buyer's Conveyancer", firm: 'Cooper Legal' },
  },
  {
    id: 'au-002',
    poolId: 'p4',
    referenceNo: 'AU-002',
    propertyAddress: '15 King William Road',
    suburb: 'Unley SA 5061, Australia',
    country: 'AU',
    countryLabel: 'Australia',
    purchasePrice: 1200000,
    currency: 'AUD',
    statusLabel: 'Active',
    statusColor: 'bg-blue-100 text-blue-700',
    settlementDate: '18 Jul 2026',
    daysToSettle: 58,
    conditionsMet: 0,
    conditionsTotal: 3,
    titleRef: 'CT 6701/234',
    deposit: '$120,000 AUD',
    depositPaid: false,
    parties: ['S', 'D'],
    settled: false,
    type: '5BR Heritage Home',
    beds: 5, baths: 3, parking: 2, landSize: '780 m²',
    description: 'An extraordinary opportunity to secure one of Unley\'s finest heritage homes. This magnificent 5-bedroom residence, circa 1905, has been sympathetically restored to preserve its original character while incorporating every modern amenity.\n\nOriginal Baltic pine floors, ornate fireplaces, and 3.6m decorative ceilings set the tone throughout. The chef\'s kitchen features Calacatta marble benchtops and integrated appliances. A north-facing garden, solar panels, and under-floor heating throughout complete this landmark offering.',
    features: ['Original Baltic pine floors', 'Ornate fireplaces × 4', '3.6m decorative ceilings', "Chef's kitchen with marble benchtops", 'Integrated Miele appliances', 'North-facing garden', 'Solar 6.6kW system', 'Under-floor heating'],
    notes: 'High-value property. Finance condition expires 30 May.',
    flag: '🇦🇺',
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1505873242700-f289a29e1724?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1560185007-c5ca9d2c014d?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600210492493-0946911123ea?auto=format&fit=crop&w=1200&q=80',
    ],
    agent: { name: 'David Walsh', role: "Seller's Conveyancer", firm: 'Walsh & Associates' },
  },
  {
    id: 'au-003',
    poolId: null,
    referenceNo: 'AU-003',
    propertyAddress: '8 Greenhill Road',
    suburb: 'Tusmore SA 5065, Australia',
    country: 'AU',
    countryLabel: 'Australia',
    purchasePrice: 980000,
    currency: 'AUD',
    statusLabel: 'Settled',
    statusColor: 'bg-green-100 text-green-700',
    settlementDate: '25 Apr 2026',
    daysToSettle: -1,
    conditionsMet: 0,
    conditionsTotal: 0,
    titleRef: 'CT 4219/551',
    deposit: '$98,000 AUD',
    depositPaid: true,
    parties: ['S', 'D'],
    settled: true,
    type: '4BR Executive',
    beds: 4, baths: 2, parking: 2, landSize: '540 m²',
    description: 'A premium executive residence in the prestigious suburb of Tusmore, offering an exceptional standard of living for the discerning buyer. Set across two levels, this 4-bedroom home showcases high-end finishes throughout and an enviable position moments from Burnside Village.\n\nThe lower level comprises a formal lounge, open-plan family and dining room, and a gourmet kitchen. Upstairs, the parents\' retreat includes a private balcony, double walk-in robe, and luxury ensuite. Settlement was completed via PEXA on 25 April 2026.',
    features: ['Two-level executive design', 'Gourmet kitchen', 'Parents\' retreat with balcony', 'Ducted zoned A/C', 'Home theatre', 'Double tandem garage', 'Private rear garden', 'Close to Burnside Village'],
    notes: 'Settlement completed via PEXA on 25 Apr 2026.',
    flag: '🇦🇺',
    images: [
      'https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
    ],
    agent: { name: 'Emma Wilson', role: 'Agent', firm: 'Wilson Realty' },
  },
  {
    id: 'au-004',
    poolId: 'p1',
    referenceNo: 'AU-004',
    propertyAddress: '3 Moseley Square',
    suburb: 'Glenelg SA 5045, Australia',
    country: 'AU',
    countryLabel: 'Australia',
    purchasePrice: 1450000,
    currency: 'AUD',
    statusLabel: 'Active',
    statusColor: 'bg-blue-100 text-blue-700',
    settlementDate: '5 Aug 2026',
    daysToSettle: 76,
    conditionsMet: 1,
    conditionsTotal: 3,
    titleRef: 'CT 7823/109',
    deposit: '$145,000 AUD',
    depositPaid: true,
    parties: ['M', 'P', 'D'],
    settled: false,
    type: '4BR Beachside',
    beds: 4, baths: 3, parking: 2, landSize: '490 m²',
    description: 'Positioned just 150 metres from the sparkling sands of Glenelg Beach, this stunning 4-bedroom coastal retreat is the ultimate beachside lifestyle property. Completely renovated with a contemporary coastal palette, every detail has been considered for relaxed, resort-style living.\n\nThe open-plan living and dining area is flooded with natural light and opens to a large deck overlooking the heated pool. Strata plan recently lodged. PEXA workspace is open and conditions are progressing well.',
    features: ['150m to beach', 'Heated swimming pool', 'Large entertainers\' deck', 'Open-plan living & dining', 'Gourmet kitchen', 'Master suite with ocean glimpses', 'Outdoor shower', 'Strata plan lodged'],
    notes: 'Coastal property 150m from beach. Strata plan lodged. PEXA workspace open.',
    flag: '🇦🇺',
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1200&q=80',
    ],
    agent: { name: 'Emma Wilson', role: 'Agent', firm: 'Wilson Realty' },
  },
  // ── Bali properties ─────────────────────────────────────────────────────
  {
    id: 'bali-001',
    poolId: 'p8',
    referenceNo: 'BALI-001',
    propertyAddress: 'Villa Karang Sunset',
    suburb: 'Seminyak, Bali, Indonesia',
    country: 'ID',
    countryLabel: 'Bali, Indonesia',
    purchasePrice: 485000,
    currency: 'AUD',
    statusLabel: 'Active',
    statusColor: 'bg-blue-100 text-blue-700',
    settlementDate: '15 Jun 2026',
    daysToSettle: 25,
    conditionsMet: 2,
    conditionsTotal: 4,
    titleRef: 'HGB-SMY-2241',
    deposit: '$48,500 AUD',
    depositPaid: true,
    parties: ['A', 'B', 'N'],
    settled: false,
    type: '3BR Private Villa',
    beds: 3, baths: 3, parking: 1, landSize: '650 m²',
    description: 'An exquisite 3-bedroom private villa nestled in the prestigious Seminyak enclave of Bali\'s most vibrant lifestyle precinct. Villa Karang Sunset blends traditional Balinese architecture with contemporary luxury across a lush 650m² tropical garden setting.\n\nEach bedroom features an ensuite and private garden access. The alfresco dining pavilion, sunken lounge, and resort-style pool create an atmosphere of serene island living. Offered on a 25-year leasehold with automatic 25-year renewal. Notarial deed lodged with PPAT. This is a rare opportunity to secure a piece of Bali\'s golden triangle.',
    features: ['Resort-style infinity pool', 'Three en-suite bedrooms', 'Traditional Balinese architecture', 'Alfresco dining pavilion', 'Tropical garden 650m²', 'Fully staffed (housekeeper + gardener)', 'Leasehold 25yr + 25yr renewal', 'Walking distance to Seminyak Square'],
    notes: 'Leasehold 25yr + 25yr. Notarial deed lodged with PPAT. Pool & tropical garden.',
    flag: '🇮🇩',
    images: [
      'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1596701062351-8ac031b18a13?auto=format&fit=crop&w=1200&q=80',
    ],
    agent: { name: 'Ni Luh Ayu', role: 'Bali Property Specialist', firm: 'Bali Realty Group' },
  },
  {
    id: 'bali-002',
    poolId: 'p7',
    referenceNo: 'BALI-002',
    propertyAddress: 'The Layar Private Estate',
    suburb: 'Canggu, Bali, Indonesia',
    country: 'ID',
    countryLabel: 'Bali, Indonesia',
    purchasePrice: 1850000,
    currency: 'AUD',
    statusLabel: 'Active',
    statusColor: 'bg-blue-100 text-blue-700',
    settlementDate: '30 Jul 2026',
    daysToSettle: 70,
    conditionsMet: 1,
    conditionsTotal: 5,
    titleRef: 'HGB-CGU-0887',
    deposit: '$185,000 AUD',
    depositPaid: true,
    parties: ['M', 'R', 'N', 'P'],
    settled: false,
    type: '5BR Luxury Estate',
    beds: 5, baths: 5, parking: 3, landSize: '2,400 m²',
    description: 'The Layar Private Estate represents the pinnacle of luxury Balinese living, an incomparable 5-bedroom freehold estate in the heart of Canggu, Bali\'s most cosmopolitan village. Spanning an extraordinary 2,400m² of prime land, this architectural masterpiece fuses traditional Joglo pavilion design with world-class contemporary amenities.\n\nFive private bedroom suites each feature a sunken outdoor bath and direct pool access. The main compound centres on a 25-metre infinity pool overlooking manicured rice paddies. Offered via Hak Milik (freehold) title through an Indonesian nominee structure. This is a once-in-a-generation offering in Bali\'s most coveted address.',
    features: ['25m infinity pool overlooking rice paddies', 'Five private bedroom suites', 'Sunken outdoor baths in each suite', 'Hak Milik freehold title', 'Traditional Joglo pavilion architecture', 'Full-time live-in staff (5 persons)', 'Private villa cinema', 'Fully equipped gym & spa'],
    notes: 'Freehold Hak Milik via Indonesian nominee. Infinity pool, 2,400m² land.',
    flag: '🇮🇩',
    images: [
      'https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1615460549969-36fa19521a4f?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1596701062351-8ac031b18a13?auto=format&fit=crop&w=1200&q=80',
    ],
    agent: { name: 'Wayan Sukerta', role: 'Bali Property Specialist', firm: 'Bali Realty Group' },
  },
  {
    id: 'bali-003',
    poolId: null,
    referenceNo: 'BALI-003',
    propertyAddress: 'Cliff Edge Villa Uluwatu',
    suburb: 'Uluwatu, Bali, Indonesia',
    country: 'ID',
    countryLabel: 'Bali, Indonesia',
    purchasePrice: 620000,
    currency: 'AUD',
    statusLabel: 'Settled',
    statusColor: 'bg-green-100 text-green-700',
    settlementDate: '10 Mar 2026',
    daysToSettle: -1,
    conditionsMet: 0,
    conditionsTotal: 0,
    titleRef: 'HGB-ULW-1193',
    deposit: '$62,000 AUD',
    depositPaid: true,
    parties: ['T', 'N'],
    settled: true,
    type: '3BR Ocean-View Villa',
    beds: 3, baths: 3, parking: 1, landSize: '520 m²',
    description: 'Perched dramatically on the clifftops of Uluwatu, one of Bali\'s most iconic locations, this spectacular 3-bedroom ocean-view villa offers uninterrupted 180-degree views of the Indian Ocean. Designed to maximise the jaw-dropping natural setting, floor-to-ceiling glass walls dissolve the boundary between interior and exterior living.\n\nThe property is offered on a 30-year leasehold title, now fully registered and transferred. Settlement was completed on 10 March 2026. Direct ocean views from every room make this an extraordinarily rare acquisition.',
    features: ['180° Indian Ocean views', 'Cliff-edge infinity pool', 'Floor-to-ceiling glass walls', '30-year leasehold (registered)', 'Three ocean-view suites', 'Private cliff garden', 'Sunset terrace & bar', 'Proximity to GWK Cultural Park'],
    notes: 'Leasehold 30yr. Title transferred and registered. Direct ocean view.',
    flag: '🇮🇩',
    images: [
      'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1200&q=80',
    ],
    agent: { name: 'Ni Luh Ayu', role: 'Bali Property Specialist', firm: 'Bali Realty Group' },
  },
  {
    id: 'bali-004',
    poolId: 'p9',
    referenceNo: 'BALI-004',
    propertyAddress: 'Jungle Retreat Ubud',
    suburb: 'Ubud, Bali, Indonesia',
    country: 'ID',
    countryLabel: 'Bali, Indonesia',
    purchasePrice: 395000,
    currency: 'AUD',
    statusLabel: 'Active',
    statusColor: 'bg-blue-100 text-blue-700',
    settlementDate: '22 Jun 2026',
    daysToSettle: 32,
    conditionsMet: 2,
    conditionsTotal: 3,
    titleRef: 'HGB-UBD-3312',
    deposit: '$39,500 AUD',
    depositPaid: true,
    parties: ['C', 'W', 'N'],
    settled: false,
    type: '2BR Jungle Villa',
    beds: 2, baths: 2, parking: 1, landSize: '380 m²',
    description: 'Tucked into the emerald-green jungle canopy above Ubud, Bali\'s celebrated arts and wellness capital, this intimate 2-bedroom jungle villa is a sanctuary of peace and natural beauty. Sweeping views across ancient rice terraces and tropical forest create a meditative atmosphere unlike anywhere else on earth.\n\nThe open-sided living pavilion, private plunge pool, and outdoor rain showers celebrate indoor-outdoor tropical living at its finest. Offered on a 30-year leasehold. Conditions are progressing well with settlement targeted for June 2026.',
    features: ['Rice terrace & jungle views', 'Private plunge pool', 'Open-sided living pavilion', 'Outdoor rain shower', '30-year leasehold', 'Walking distance to Ubud Palace', 'Yoga & meditation deck', 'On-site spa treatment room'],
    notes: 'Leasehold 30yr. Rice terrace views. Surrounded by tropical forest.',
    flag: '🇮🇩',
    images: [
      'https://images.unsplash.com/photo-1555400038-63f5ba517a47?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1562790351-d273a961e0e9?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1200&q=80',
    ],
    agent: { name: 'Wayan Sukerta', role: 'Bali Property Specialist', firm: 'Bali Realty Group' },
  },
  {
    id: 'bali-005',
    poolId: null,
    referenceNo: 'BALI-005',
    propertyAddress: 'Nusa Dua Beachfront Villa',
    suburb: 'Nusa Dua, Bali, Indonesia',
    country: 'ID',
    countryLabel: 'Bali, Indonesia',
    purchasePrice: 2200000,
    currency: 'AUD',
    statusLabel: 'Active',
    statusColor: 'bg-blue-100 text-blue-700',
    settlementDate: '15 Sep 2026',
    daysToSettle: 117,
    conditionsMet: 0,
    conditionsTotal: 4,
    titleRef: 'HGB-NSD-0551',
    deposit: '$220,000 AUD',
    depositPaid: false,
    parties: ['H', 'K', 'N'],
    settled: false,
    type: '6BR Beachfront Estate',
    beds: 6, baths: 6, parking: 4, landSize: '4,000 m²',
    description: 'The most exceptional private beachfront estate to be offered in Nusa Dua in a generation. Spanning an unprecedented 4,000m² of direct beachfront land in Bali\'s most prestigious resort precinct, this 6-bedroom masterpiece commands an irreplaceable position on the white sands of Nusa Dua Beach.\n\nThe estate features a 35-metre lagoon pool, private beach club pavilion, 8-car garage, and fully staffed operations for immediate occupation. Offered with Hak Milik (freehold) title — the highest form of land ownership available in Indonesia. An unparalleled trophy asset.',
    features: ['Direct private beach access', '35m lagoon-style pool', 'Six beachfront suite pavilions', 'Hak Milik freehold title', 'Private beach club pavilion', '4,000m² beachfront land', 'Full-time staff team (8 persons)', '8-car garage + motorcycle bays'],
    notes: 'Direct beachfront. Hak Milik title. 4,000m² land with private beach access.',
    flag: '🇮🇩',
    images: [
      'https://images.unsplash.com/photo-1615460549969-36fa19521a4f?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1200&q=80',
    ],
    agent: { name: 'Wayan Sukerta', role: 'Bali Property Specialist', firm: 'Bali Realty Group' },
  },
  {
    id: 'bali-006',
    poolId: null,
    referenceNo: 'BALI-006',
    propertyAddress: 'Sanur Sunrise Residence',
    suburb: 'Sanur, Bali, Indonesia',
    country: 'ID',
    countryLabel: 'Bali, Indonesia',
    purchasePrice: 520000,
    currency: 'AUD',
    statusLabel: 'Settled',
    statusColor: 'bg-green-100 text-green-700',
    settlementDate: '5 Feb 2026',
    daysToSettle: -1,
    conditionsMet: 0,
    conditionsTotal: 0,
    titleRef: 'HGB-SNR-2078',
    deposit: '$52,000 AUD',
    depositPaid: true,
    parties: ['F', 'G'],
    settled: true,
    type: '3BR Garden Villa',
    beds: 3, baths: 3, parking: 1, landSize: '800 m²',
    description: 'A beautifully serene 3-bedroom garden villa in the genteel seaside enclave of Sanur, Bali\'s most relaxed beachside village. Set across a lush 800m² tropical garden, the residence exudes timeless charm with its traditional Balinese architecture and contemporary comforts.\n\nJust 800 metres from Sanur\'s famous sunrise beach, the villa features a private pool, outdoor dining bale, and a tranquil garden filled with frangipani and heliconia. Settlement was completed in February 2026, with the 25-year leasehold title fully registered.',
    features: ['800m to Sanur Beach', 'Private garden pool', 'Traditional outdoor dining bale', '800m² tropical garden', '25-year leasehold (registered)', 'Three en-suite bedrooms', 'Outdoor kitchen & BBQ', 'Mature tropical garden plantings'],
    notes: 'Leasehold 25yr. 800m to beach. Settlement completed.',
    flag: '🇮🇩',
    images: [
      'https://images.unsplash.com/photo-1562790351-d273a961e0e9?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1555400038-63f5ba517a47?auto=format&fit=crop&w=1200&q=80',
    ],
    agent: { name: 'Ni Luh Ayu', role: 'Bali Property Specialist', firm: 'Bali Realty Group' },
  },
];
